# Generated by Django 4.0.4 on 2022-06-01 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('in_queue', 'Поставлена в очередь'), ('running', 'Выполняется'), ('stopped', 'Приостановлена'), ('executed', 'Завершена'), ('deleted', 'Удалена')], default='in_queue', max_length=50, verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='path',
            field=models.CharField(max_length=200, verbose_name='Путь к исполняемому файлу'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
