# Generated by Django 4.0.4 on 2022-06-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер в очереди'),
        ),
    ]
