# Generated by Django 4.0.4 on 2022-06-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task', verbose_name='Задача'),
        ),
    ]
